-- MontaPC: infraestrutura de preços reais e histórico.
-- O frontend pode ler preços, mas não inserir/alterar snapshots.

create table if not exists public.montapc_price_snapshots (
  id bigint generated by default as identity primary key,
  component_id uuid not null references public.montapc_components(id) on delete cascade,
  store_name text not null check (char_length(trim(store_name)) between 1 and 120),
  price_cents integer not null check (price_cents > 0),
  product_url text,
  in_stock boolean not null default true,
  source_type text not null default 'api'
    check (source_type in ('api','feed','manual','affiliate')),
  observed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists montapc_price_snapshots_component_observed_idx
  on public.montapc_price_snapshots(component_id, observed_at desc);

create index if not exists montapc_price_snapshots_store_idx
  on public.montapc_price_snapshots(store_name);

alter table public.montapc_price_snapshots enable row level security;

drop policy if exists "montapc prices public read" on public.montapc_price_snapshots;
create policy "montapc prices public read"
  on public.montapc_price_snapshots
  for select
  to anon, authenticated
  using (true);

comment on table public.montapc_price_snapshots is
  'Historical observed store prices for MontaPC. Client has read-only access; ingestion must happen server-side.';
