-- MontaPC: analytics anônimo de produto.
-- Não armazena e-mail, nome, IP ou conteúdo integral das builds.

create table if not exists public.montapc_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null,
  user_id uuid null references auth.users(id) on delete set null,
  event_name text not null check (
    event_name in (
      'page_view',
      'build_generated',
      'part_swapped',
      'build_saved',
      'build_shared',
      'compare_used',
      'language_changed',
      'pwa_install_clicked'
    )
  ),
  locale text not null default 'pt-BR' check (locale in ('pt-BR','en')),
  viewport text not null check (viewport in ('mobile','tablet','desktop')),
  context jsonb not null default '{}'::jsonb
    check (jsonb_typeof(context) = 'object' and octet_length(context::text) <= 4000),
  created_at timestamptz not null default now()
);

create index if not exists montapc_events_created_idx
  on public.montapc_events(created_at desc);

create index if not exists montapc_events_name_created_idx
  on public.montapc_events(event_name, created_at desc);

alter table public.montapc_events enable row level security;

drop policy if exists "montapc events insert" on public.montapc_events;
create policy "montapc events insert"
  on public.montapc_events
  for insert
  to anon, authenticated
  with check (
    user_id is null or user_id = (select auth.uid())
  );
