-- MontaPC: feedback de beta para validação com usuários reais.
create table if not exists public.montapc_feedback (
  id bigint generated by default as identity primary key,
  session_id uuid not null,
  user_id uuid null references auth.users(id) on delete set null,
  rating smallint not null check (rating between 1 and 5),
  category text not null check (category in ('usability','recommendation','compatibility','bug','idea')),
  comment text not null check (char_length(trim(comment)) between 2 and 1000),
  locale text not null default 'pt-BR' check (locale in ('pt-BR','en')),
  viewport text not null check (viewport in ('mobile','tablet','desktop')),
  created_at timestamptz not null default now()
);

create index if not exists montapc_feedback_created_idx
  on public.montapc_feedback(created_at desc);

alter table public.montapc_feedback enable row level security;

drop policy if exists "montapc feedback insert" on public.montapc_feedback;
create policy "montapc feedback insert"
  on public.montapc_feedback
  for insert
  to anon, authenticated
  with check (user_id is null or user_id = (select auth.uid()));
